stages:
  - login     
  - build
  - publish
  - clear
  - runner
  - logout


nexus-login:
  stage: login
  script : 
    - docker logout
    - echo $NEXUS_REGISTRY
    - echo "$NEXUS_PASSWORD" | docker login $NEXUS_REGISTRY --username "$NEXUS_USERNAME" --password-stdin


build-cloud:      
  stage: build
  needs:
    - nexus-login
  script:
    - echo "Build Cloud"
    - echo $CI_COMMIT_SHA
    - docker build --build-arg BASE_PATH=/cloud --no-cache -f dockerfile-cloud -t $NEXUS_IMAGE_REPO/crepen-cdn-cloud:$CI_COMMIT_SHA .
    - docker tag $NEXUS_IMAGE_REPO/crepen-cdn-cloud:$CI_COMMIT_SHA $NEXUS_IMAGE_REPO/crepen-cdn-cloud:latest



build-server:
  stage : build
  needs:
    - nexus-login
  script : 
    - echo "Build Server"
    - echo $CI_COMMIT_SHA
    - ls


publish-cloud:
  stage: publish
  needs:
    - build-cloud
  script: 
    - docker push $NEXUS_IMAGE_REPO/crepen-cdn-cloud:$CI_COMMIT_SHA
    - docker push $NEXUS_IMAGE_REPO/crepen-cdn-cloud:latest


publish-server:
  stage: publish
  needs:
    - build-server
  script: 
    - cat ~/.docker/config.json




clear-image:
  stage: clear
  needs:
    - publish-cloud
    - publish-server
  script:
    - docker image prune -a



run-cloud : 
  stage: runner
  needs:
    - publish-cloud
    - clear-image
  script : 
    - echo "Run Cloud"
    - echo $CI_COMMIT_SHA
    - docker ps


run-server : 
  stage: runner
  needs:
    - publish-server
    - clear-image
  script : 
    - echo "Run Server"
    - echo $CI_COMMIT_SHA
    - docker ps




nexus-logout:
  stage: logout
  needs:
    - run-server
    - run-cloud
  script:
    - docker logout $NEXUS_REGISTRY

    