stages:     
  - build
  - runner

build-cloud:      
  stage: build
  script:
    - echo "Build Cloud"
    - echo $CI_COMMIT_SHA
    - docker build --build-arg BASE_PATH=/cloud -f dockerfile-cloud -t crepen-cdn-cloud:$CI_COMMIT_SHA .



build-server:
  stage : build
  script : 
    - echo "Build Server"
    - echo $CI_COMMIT_SHA
    - ls

run-cloud : 
  stage: runner
  needs:
    - build-cloud
  script : 
    - echo "Run Cloud"
    - echo $CI_COMMIT_SHA
    - docker ps


run-server : 
  stage: runner
  needs:
    - build-server
  script : 
    - echo "Run Server"
    - echo $CI_COMMIT_SHA
    - docker ps




    