stages:
  - login     
  - build
  - publish
  - runner


docker-login:
  stage: login
  script : 
    - echo "$NEXUS_PASSWORD"
    - echo "$NEXUS_REGISTRY"
    - echo "$NEXUS_USERNAME"


build-cloud:      
  stage: build
  script:
    - echo "Build Cloud"
    - echo $CI_COMMIT_SHA
    - docker build --build-arg BASE_PATH=/cloud --no-cache -f dockerfile-cloud -t crepen-cdn-cloud:$CI_COMMIT_SHA .



build-server:
  stage : build
  script : 
    - echo "Build Server"
    - echo $CI_COMMIT_SHA
    - ls


publish-cloud:
  stage: publish
  needs:
    - build-cloud
  script: 
    - cat ~/.docker/config.json


publish-server:
  stage: publish
  needs:
    - build-server
  script: 
    - cat ~/.docker/config.json


run-cloud : 
  stage: runner
  needs:
    - publish-cloud
  script : 
    - echo "Run Cloud"
    - echo $CI_COMMIT_SHA
    - docker ps


run-server : 
  stage: runner
  needs:
    - publish-server
  script : 
    - echo "Run Server"
    - echo $CI_COMMIT_SHA
    - docker ps




    