stages:
  - login     
  - build
  - publish
  - clear
  - check-network
  - runner
  - logout


nexus-login:
  stage: login
  script : 
    - docker logout
    - echo $NEXUS_REGISTRY
    - echo "$NEXUS_PASSWORD" | docker login $NEXUS_REGISTRY --username "$NEXUS_USERNAME" --password-stdin


# build-cloud:      
#   stage: build
#   needs:
#     - nexus-login
#   script:
#     - docker build --build-arg BASE_PATH=/cloud --no-cache -f dockerfile-cloud -t $NEXUS_IMAGE_REPO/crepen-cdn-cloud:$CI_COMMIT_SHA .
#     - docker tag $NEXUS_IMAGE_REPO/crepen-cdn-cloud:$CI_COMMIT_SHA $NEXUS_IMAGE_REPO/crepen-cdn-cloud:latest



build-server:
  stage : build
  needs:
    - nexus-login
  script : 
    - docker build --build-arg --no-cache -f dockerfile-server -t $NEXUS_IMAGE_REPO/crepen-cdn-server:$CI_COMMIT_SHA .
    - docker tag $NEXUS_IMAGE_REPO/crepen-cdn-server:$CI_COMMIT_SHA $NEXUS_IMAGE_REPO/crepen-cdn-server:latest

# publish-cloud:
#   stage: publish
#   needs:
#     - build-cloud
#   script: 
#     - docker push $NEXUS_IMAGE_REPO/crepen-cdn-cloud:$CI_COMMIT_SHA
#     - docker push $NEXUS_IMAGE_REPO/crepen-cdn-cloud:latest


publish-server:
  stage: publish
  needs:
    - build-server
  script: 
    - docker push $NEXUS_IMAGE_REPO/crepen-cdn-server:$CI_COMMIT_SHA
    - docker push $NEXUS_IMAGE_REPO/crepen-cdn-server:latest




clear-image:
  stage: clear
  needs:
    # - publish-cloud
    - publish-server
  script:
    - docker image prune -a -f


check-nginx-network:
  stage: check-network
  needs:
    - clear-image
  script:
    - echo "Docker 네트워크 존재 여부 확인..."
    - |
      if ! docker network ls --format '{{.Name}}' | grep -q '^nginx-network$'; then
        echo "네트워크가 존재하지 않습니다. 생성 중..."
        docker network create nginx-network
      else
        echo "네트워크가 이미 존재합니다."
      fi

check-crepen-cdn-network:
  stage: check-network
  needs:
    - clear-image
  script:
    - echo "Docker 네트워크 존재 여부 확인..."
    - |
      if ! docker network ls --format '{{.Name}}' | grep -q '^crepen-cdn-network$'; then
        echo "네트워크가 존재하지 않습니다. 생성 중..."
        docker network create crepen-cdn-network
      else
        echo "네트워크가 이미 존재합니다."
      fi


# run-cloud : 
#   stage: runner
#   needs:
#     - publish-cloud
#     - check-nginx-network
#     - check-crepen-cdn-network
#   script : 
#     - docker rm -f crepen-cdn-cloud
#     - docker run -d --name crepen-cdn-cloud -e API_URL=http://crepen-cdn-server:13332 --hostname crepen-cdn-cloud  $NEXUS_IMAGE_REPO/crepen-cdn-cloud:latest
#     - docker network connect nginx-network crepen-cdn-cloud
#     - docker network connect crepen-cdn-network crepen-cdn-cloud


run-server : 
  stage: runner
  needs:
    - publish-server
    - check-nginx-network
    - check-crepen-cdn-network
  script : 
    - docker rm -f crepen-cdn-server
    - docker run -d --name crepen-cdn-server --hostname crepen-cdn-server  $NEXUS_IMAGE_REPO/crepen-cdn-server:latest
    - docker network connect crepen-cdn-network crepen-cdn-server




nexus-logout:
  stage: logout
  needs:
    - run-server
    # - run-cloud
  script:
    - docker logout $NEXUS_REGISTRY

    