
FROM node:22-alpine AS builder 

ENV BASE_PATH=/

RUN echo BASEPATH: $BASE_PATH

WORKDIR /app

COPY . .


RUN yarn

RUN yarn admin build


FROM node:22-alpine AS runner

WORKDIR /app

COPY --from=builder /app/apps/admin/next.config.ts ./
COPY --from=builder /app/apps/admin/package.json ./
COPY --from=builder --chown=nextjs:nodejs /app/apps/admin/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/apps/admin/.next/static ./apps/admin/.next/static
COPY --from=builder --chown=nextjs:nodejs /app/apps/admin/public ./apps/admin/public

ENV HOSTNAME=0.0.0.0
ENV PORT=3000
ENV API_URL=http://crepen-cdn-server:13332

EXPOSE 3000

CMD ["node", "apps/admin/server.js"]


