
FROM node:22-alpine AS builder 

ENV BASE_PATH=/cloud

RUN echo BASEPATH: $BASE_PATH

WORKDIR /app

COPY . .


RUN yarn

RUN yarn cloud build


FROM node:22-alpine AS runner

WORKDIR /app

COPY --from=builder /app/apps/cloud/next.config.ts ./
COPY --from=builder /app/apps/cloud/package.json ./
COPY --from=builder --chown=nextjs:nodejs /app/apps/cloud/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/apps/cloud/.next/static ./apps/cloud/.next/static
COPY --from=builder --chown=nextjs:nodejs /app/apps/cloud/public ./apps/cloud/public

ENV HOSTNAME=0.0.0.0
ENV PORT=3000

CMD ["node", "apps/cloud/server.js"]


