



FROM node:22-alpine AS builder

WORKDIR /app
COPY . .

RUN yarn
RUN yarn server build


FROM node:22-alpine AS runner

WORKDIR /app

RUN mkdir /var/opt/crepen/cdn -p
# RUN chown -R 1001:1001 /var/opt/crepen/cdn
RUN mkdir /var/log/crepen/cdn -p
# RUN chown -R 1001:1001 /var/log/crepen/cdn
RUN mkdir /etc/crepen/cdn -p
# RUN chown -R 1001:1001 /etc/crepen/cdn


# RUN addgroup --system --gid 1001 nodejs
# RUN adduser --system --uid 1001 nestjs

# USER nestjs

RUN apk add --no-cache curl bash

COPY --from=builder --chown=nestjs:nodejs /app/apps/server/package.json ./
COPY --from=builder --chown=nestjs:nodejs /app/apps/server/node_modules ./node_modules
COPY --from=builder --chown=nestjs:nodejs /app/node_modules ./node_modules
COPY --from=builder --chown=nestjs:nodejs /app/apps/server/dist ./dist





ENV HOSTNAME=0.0.0.0
ENV PORT=13332

ENV CREPEN_CDN_DATA_DIR=/var/opt/crepen/cdn
ENV CREPEN_CDN_LOG_DIR=/var/log/crepen/cdn
ENV CREPEN_CDN_CONFIG_DIR=/etc/crepen/cdn
ENV CREPEN_CDN_PORT=13332


CMD ["node", "dist/main.js"]














# # ========== Builder ========== #
# FROM node:22-alpine AS builder
# RUN apk add --no-cache libc6-compat && apk update

# WORKDIR /app

# # Turbo globally
# RUN yarn global add turbo

# # 전체 코드 복사
# COPY . .

# # Turborepo prune
# RUN turbo prune --scope=@crepen-cdn/server --docker

# # ========== Installer ========== #
# FROM node:22-alpine AS installer
# RUN apk add --no-cache libc6-compat && apk update

# WORKDIR /app

# # 필요한 파일만 복사
# COPY .gitignore .gitignore
# COPY --from=builder /app/out/json/ ./
# COPY --from=builder /app/out/yarn.lock ./yarn.lock

# # 의존성 설치
# RUN yarn install --frozen-lockfile

# # 전체 소스 복사 (의존성 기준으로 빌드)
# COPY --from=builder /app/out/full/ ./
# COPY turbo.json turbo.json

# # 빌드 실행
# RUN yarn turbo run build --filter=@crepen-cdn/server...

# # # ========== Runner ========== #
# FROM node:22-alpine AS runner
# WORKDIR /app

# RUN mkdir /var/opt/crepen/cdn -p
# RUN chown -R 1001:1001 /var/opt/crepen/cdn

# RUN mkdir /var/log/crepen/cdn -p
# RUN chown -R 1001:1001 /var/log/crepen/cdn



# # 보안용 non-root 유저 추가
# RUN addgroup --system --gid 1001 nodejs
# RUN adduser --system --uid 1001 nestjs
# USER nestjs


# ENV CREPEN_CDN_DATA_DIR=/var/opt/crepen/cdn
# ENV CREPEN_CDN_LOG_DIR=/var/log/crepen/cdn
# ENV CREPEN_CDN_PORT=13332


# # 앱 실행에 필요한 파일만 복사
# # COPY --from=installer /app/apps/server/.env ./
# COPY --from=installer /app/apps/server/package.json ./
# COPY --from=installer /app/apps/server/node_modules ./node_modules
# COPY --from=installer /app/node_modules ./node_modules
# COPY --from=installer --chown=nestjs:nodejs /app/apps/server/dist ./dist

# # 앱 실행
# CMD ["node", "dist/main.js"]





