server:
  port: 3333
db:
  host: 'localhost'
  port: 3306
  database: 'crepencdn'
  username: 'crepen'
  password: 'qwer1234'
secret:
  auth: 'test-secret'
  jwt : 'test-jwt-secret'
jwt : 
  secret : 'test-jwt-secret'
  expireTime : 3600s

