type MimeCategoryType = 'other' | 'image' | 'video' | 'zip' | 'audio' | 'text'

export class MimeUtil {
    static getCategory = (mime: string): MimeCategoryType => {
        if (Object.keys(this.MIME_TYPE).indexOf(mime) > -1) {
            return this.MIME_TYPE[mime] as MimeCategoryType || 'other';
        }
        else {
            return 'other';
        }
    }






    private static MIME_TYPE: Record<string, string> = {
        "application/javascript": "other",
        "application/json": "other",
        "application/manifest+json": "other",
        "application/msword": "other",
        "application/n-quads": "other",
        "application/n-triples": "other",
        "application/octet-stream": "other",
        "application/oda": "other",
        "application/pdf": "other",
        "application/pkcs7-mime": "other",
        "application/postscript": "other",
        "application/trig": "other",
        "application/vnd.apple.mpegurl": "other",
        "application/vnd.ms-excel": "other",
        "application/vnd.ms-powerpoint": "other",
        "application/wasm": "other",
        "application/x-bcpio": "other",
        "application/x-cpio": "other",
        "application/x-csh": "other",
        "application/x-dvi": "other",
        "application/x-gtar": "other",
        "application/x-hdf": "other",
        "application/x-hdf5": "other",
        "application/x-latex": "other",
        "application/x-mif": "other",
        "application/x-netcdf": "other",
        "application/x-pkcs12": "other",
        "application/x-pn-realaudio": "other",
        "application/x-python-code": "other",
        "application/x-sh": "other",
        "application/x-shar": "other",
        "application/x-shockwave-flash": "other",
        "application/x-sv4cpio": "other",
        "application/x-sv4crc": "other",
        "application/x-tar": "other",
        "application/x-tcl": "other",
        "application/x-tex": "other",
        "application/x-texinfo": "other",
        "application/x-troff": "other",
        "application/x-troff-man": "other",
        "application/x-troff-me": "other",
        "application/x-troff-ms": "other",
        "application/x-ustar": "other",
        "application/x-wais-source": "other",
        "application/xml": "other",
        "message/rfc822": "other",
        "application/zip": "zip",
        "audio/3gpp": "audio",
        "audio/3gpp2": "audio",
        "audio/aac": "audio",
        "audio/basic": "audio",
        "audio/mpeg": "audio",
        "audio/opus": "audio",
        "audio/x-aiff": "audio",
        "audio/x-pn-realaudio": "audio",
        "audio/x-wav": "audio",
        "image/avif": "image",
        "image/bmp": "image",
        "image/gif": "image",
        "image/ief": "image",
        "image/jpeg": "image",
        "image/heic": "image",
        "image/heif": "image",
        "image/png": "image",
        "image/svg+xml": "image",
        "image/tiff": "image",
        "image/vnd.microsoft.icon": "image",
        "image/x-cmu-raster": "image",
        "image/x-portable-anymap": "image",
        "image/x-portable-bitmap": "image",
        "image/x-portable-graymap": "image",
        "image/x-portable-pixmap": "image",
        "image/x-rgb": "image",
        "image/x-xbitmap": "image",
        "image/x-xpixmap": "image",
        "image/x-xwindowdump": "image",
        "text/css": "text",
        "text/csv": "text",
        "text/html": "text",
        "text/n3": "text",
        "text/plain": "text",
        "text/richtext": "text",
        "text/tab-separated-values": "text",
        "text/vtt": "text",
        "text/x-python": "text",
        "text/x-setext": "text",
        "text/x-sgml": "text",
        "text/x-vcard": "text",
        "text/xml": "text",
        "video/mp4": "video",
        "video/mpeg": "video",
        "video/quicktime": "video",
        "video/webm": "video",
        "video/x-msvideo": "video",
        "video/x-sgi-movie": "video"
    }
}